### ISSUE TITLE
Remove linked folder/files "AntiSamyPolicyExamples" from project

### ISSUE THREAD

**Issue by jappjapp** [spassarop/antisamy-dotnet#11]
**Is your feature request related to a problem? Please describe.**
When restoring a net 6.0 project that has a dependency on AntiSamy 1.1.1, a folder appears in the project root:  "AntiSamyPolicyExamples". It's a link to files in the nuget cache folder in C:\users\myuser.

The folder content is helpful when setting up Antisamy, but when I'm done (when I have edited an xml config file to my requirements, and moved it to a proper location in the project), I'd like to remove the "AntiSamyPolicyExample" folder/link from the project.

Removing that folder adds the following to the csproj:
```xml
  <ItemGroup>
    <Content Remove="C:\Users\myuser\.nuget\packages\owasp.antisamy\1.1.1\contentFiles\any\net6.0\AntiSamyPolicyExamples\antisamy-anythinggoes.xml" />
    <Content Remove="C:\Users\myuser\.nuget\packages\owasp.antisamy\1.1.1\contentFiles\any\net6.0\AntiSamyPolicyExamples\antisamy-ebay.xml" />
    <Content Remove="C:\Users\myuser\.nuget\packages\owasp.antisamy\1.1.1\contentFiles\any\net6.0\AntiSamyPolicyExamples\antisamy-myspace.xml" />
    <Content Remove="C:\Users\myuser\.nuget\packages\owasp.antisamy\1.1.1\contentFiles\any\net6.0\AntiSamyPolicyExamples\antisamy-slashdot.xml" />
    <Content Remove="C:\Users\myuser\.nuget\packages\owasp.antisamy\1.1.1\contentFiles\any\net6.0\AntiSamyPolicyExamples\antisamy-tinymce.xml" />
    <Content Remove="C:\Users\myuser\.nuget\packages\owasp.antisamy\1.1.1\contentFiles\any\net6.0\AntiSamyPolicyExamples\antisamy.xml" />
    <Content Remove="C:\Users\myuser\.nuget\packages\owasp.antisamy\1.1.1\contentFiles\any\net6.0\AntiSamyPolicyExamples\antisamy.xsd" />
  </ItemGroup>
```

Problems with above:
- myuser is forever listed in the csproj, that's not great in corporate/consulting/opensource scenarios
- the CI/CD build pipeline will choke on a non-existing path

**Describe the solution you'd like**
Don't make the nuget package put a folder reference in the project on restore. Tell the user that the appropriate setting files must be manually added to the project in a folder of their own choice.

**Describe alternatives you've considered**
I haven't found a way to write a Condition-attribute on the Content or ItemGroup xml-tags in the csproj example above, that would ignore the the tags under circumstances that are relevant to my CI/CD pipeline.

Thanks!

**Comment by spassarop** [comment]
Sorry I reply so late. I get what you mean, I tried to make the setup easier and never considered that scenario. I'll check if there is a way to prevent that issue and if I can't find a solution then I'll just have to add a big note about getting the policy examples.

Thanks for your report.

**Comment by spassarop** [comment]
I removed the references to not be included in future packages releases. Users must include their own policies manually, stated in the README of the project+package and GitHub wiki.

@jappjapp could you verify and close if you are still using it?

**Comment by spassarop** [comment]
Many time has passed since the release that covered this. Closing the issue.
